# -  /vinnytech453/

FROM quay.io/vinnytech453/vinnytech453-v2
RUN git clone https://github.com/vinnytech453/vinnytech453 /root/vinni23
WORKDIR /root/vinni23/
RUN npm install
EXPOSE 8000
CMD ["npm","start" ] 
  
# -  /vinnytech453/ Don't change this name,

